steps:
  - name: 'golang:1.16'
    entrypoint: 'go'
    dir: 'cloudrun/secrets'
    args: ['build', '-o', 'app', '.']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-secrets/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
      - --dockerfile=cloudrun/secrets/Dockerfile
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - beta
      - run
      - deploy
      - secrets-reader
      - --region=asia-northeast1
      - --platform=managed
      - --service-account=cloudrun@$PROJECT_ID.iam.gserviceaccount.com
      - --max-instances=1
      - --cpu=1
      - --memory=256Mi
      - --concurrency=8
      - --allow-unauthenticated
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-secrets/$BRANCH_NAME:$COMMIT_SHA
      - --set-secrets=SECRET_ENV1=SECRET_ENV1:latest
      - --set-secrets=SECRET_ENV2=SECRET_ENV2:latest
      - --set-secrets=/etc/secrets/file1/body=SECRET_FILE1:latest
      - --set-secrets=/etc/secrets/file2/body=SECRET_FILE2:latest